export const CREATE_EVENT = "CREATE_EVENT"
export const DELETE_EVENT = "DELETE_EVENT"
export const DELETE_ALL_EVENTS = "DELETE_ALL_EVENTS"

export const ADD_OPERATION_LOS = "ADD_OPERATION_LOS"
export const ADD_ALL_OPERATION_LOS = "ADD_ALL_OPERATION_LOS"
